// THIS FILE IS AUTO-GENERATED by scripts/gen-version.mjs
// Do not edit manually; run npm run build (or invoke script) instead.
export const APP_VERSION = '2025.09.29-004840-d421633';
if (typeof window !== 'undefined') {
  window.__APP_VERSION__ = window.__APP_VERSION__ || APP_VERSION;
}
