#!/usr/bin/env node
/**
 * Version generation script.
 *
 * Generates:
 *  - src/version.js   (export const APP_VERSION = '...')
 *  - public/version.json (runtime-readable manifest)
 *
 * Version format (default): YYYY.MM.DD-build[+meta]
 *  build part defaults to an incrementing HHMMSS timestamp or GIT short SHA if available.
 *
 * Environment overrides:
 *  APP_VERSION=explicit            Provide exact version string (bypasses auto format)
 *  BUILD_META=foo                  Appended after '+' (e.g. 2025.09.25-123045+foo)
 *  CRITICAL_UPDATE=true            Sets manifest critical=true
 *  MIN_CLIENT=2025.09.01-00        Sets minClient field (forces update for older clients)
 *  VERSION_CHANNEL=DEV|RC|PROD     Optional channel suffix in build section
 *
 * Safety: Will not downgrade version unless FORCE_VERSION_DOWNGRADE=true
 */
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { execSync } from 'child_process';
import path from 'path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const SRC_VERSION_FILE = path.join(ROOT, 'src', 'version.js');
const PUBLIC_VERSION_FILE = path.join(ROOT, 'public', 'version.json');
const PUBLIC_SW_VERSION_FILE = path.join(ROOT, 'public', 'sw-version.js');

function getGitShortSha() {
  try {
    return execSync('git rev-parse --short HEAD', { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

function readCurrentManifest() {
  if (!existsSync(PUBLIC_VERSION_FILE)) return null;
  try {
    return JSON.parse(readFileSync(PUBLIC_VERSION_FILE, 'utf8'));
  } catch {
    return null;
  }
}

function parseVersion(v) {
  if (!v) return null;
  const idx = v.indexOf('-');
  if (idx === -1) return { date: v, build: '' };
  return { date: v.slice(0, idx), build: v.slice(idx + 1) };
}

function compareVersions(a, b) {
  if (a === b) return 0;
  const pa = parseVersion(a);
  const pb = parseVersion(b);
  if (!pa || !pb) return a > b ? 1 : -1; // fallback
  if (pa.date !== pb.date) return pa.date > pb.date ? 1 : -1; // dates lexically safe

  const aStartsDigit = /^[0-9]/.test(pa.build);
  const bStartsDigit = /^[0-9]/.test(pb.build);

  // If one starts numeric (timestamp) and the other not, numeric is newer
  if (aStartsDigit && !bStartsDigit) return 1;
  if (!aStartsDigit && bStartsDigit) return -1;

  // If both numeric, compare first 6 digits (HHMMSS) if present
  const aTime = aStartsDigit ? pa.build.slice(0, 6) : '';
  const bTime = bStartsDigit ? pb.build.slice(0, 6) : '';
  const timeNumeric = /^[0-9]{6}$/;
  if (timeNumeric.test(aTime) && timeNumeric.test(bTime) && aTime !== bTime) {
    return aTime > bTime ? 1 : -1;
  }

  // Fallback lexical for remainder (covers sha, channel, meta)
  return pa.build > pb.build ? 1 : -1;
}

function generateVersion() {
  if (process.env.APP_VERSION) return process.env.APP_VERSION.trim();
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(now.getUTCDate()).padStart(2, '0');
  const hh = String(now.getUTCHours()).padStart(2, '0');
  const min = String(now.getUTCMinutes()).padStart(2, '0');
  const ss = String(now.getUTCSeconds()).padStart(2, '0');
  const sha = getGitShortSha();
  const buildCore = `${hh}${min}${ss}`;
  let build = sha ? `${buildCore}-${sha}` : buildCore;
  if (process.env.VERSION_CHANNEL) build += `-${process.env.VERSION_CHANNEL}`;
  const meta = process.env.BUILD_META ? `+${process.env.BUILD_META}` : '';
  return `${yyyy}.${mm}.${dd}-${build}${meta}`;
}

const manifestPrev = readCurrentManifest();
const newVersion = generateVersion();

if (
  manifestPrev &&
  compareVersions(newVersion, manifestPrev.appVersion) < 0 &&
  process.env.FORCE_VERSION_DOWNGRADE !== 'true'
) {
  console.error(`Refusing to write older version ${newVersion} < ${manifestPrev.appVersion}. Set FORCE_VERSION_DOWNGRADE=true to override.`);
  process.exit(1);
}

const critical = process.env.CRITICAL_UPDATE === 'true';
const minClient = process.env.MIN_CLIENT || (manifestPrev?.minClient || `${new Date().getUTCFullYear()}.01.01-00`);

const buildInfo = {
  appVersion: newVersion,
  build: process.env.BUILD_ID || process.env.BUILD_NUMBER || 'local',
  critical,
  minClient
};

// Write version.js
const versionJs = `// THIS FILE IS AUTO-GENERATED by scripts/gen-version.mjs\n// Do not edit manually; run npm run build (or invoke script) instead.\nexport const APP_VERSION = '${newVersion}';\nif (typeof window !== 'undefined') {\n  window.__APP_VERSION__ = window.__APP_VERSION__ || APP_VERSION;\n}\n`;
writeFileSync(SRC_VERSION_FILE, versionJs, 'utf8');

// Write version.json (pretty for easy diff)
writeFileSync(PUBLIC_VERSION_FILE, JSON.stringify(buildInfo, null, 2) + '\n', 'utf8');

// Write a small service worker companion so the SW cache namespace rotates on every build.
writeFileSync(
  PUBLIC_SW_VERSION_FILE,
  `self.__MIMIR_SW_VERSION__ = '${newVersion}';\n`,
  'utf8'
);

console.log(`Generated version: ${newVersion}`);
console.log(`Critical: ${critical}  minClient: ${minClient}`);
