// Copyright (C) 2026 Ryan Lane
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

// THIS FILE IS AUTO-GENERATED by scripts/gen-version.mjs
// Do not edit manually; run npm run build (or invoke script) instead.
export const APP_VERSION = '2026.06.14-030831-7a01a27';
if (typeof window !== 'undefined') {
  window.__APP_VERSION__ = window.__APP_VERSION__ || APP_VERSION;
}
