# Copyright (C) 2026 Ryan Lane
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Initial complete schema

Revision ID: 9f3f58276f60
Revises:
Create Date: 2025-08-26 15:43:00.687710

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f3f58276f60'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('repo_url', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channels_created_at', 'channels', ['created_at'], unique=False)
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=False)
    op.create_index('ix_channels_name_version', 'channels', ['name', 'version'], unique=False)
    op.create_index(op.f('ix_channels_schema_version'), 'channels', ['schema_version'], unique=False)
    op.create_table('overlays',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('overlay_type', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overlays_created_at'), 'overlays', ['created_at'], unique=False)
    op.create_index(op.f('ix_overlays_name'), 'overlays', ['name'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('overlays', sa.JSON(), nullable=True),
    sa.Column('timing_config', sa.JSON(), nullable=True),
    sa.Column('distribution_mode', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('content_epoch', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenes_active_distribution', 'scenes', ['is_active', 'distribution_mode'], unique=False)
    op.create_index(op.f('ix_scenes_content_epoch'), 'scenes', ['content_epoch'], unique=False)
    op.create_index(op.f('ix_scenes_content_hash'), 'scenes', ['content_hash'], unique=False)
    op.create_index('ix_scenes_content_hash_epoch', 'scenes', ['content_hash', 'content_epoch'], unique=False)
    op.create_index(op.f('ix_scenes_created_at'), 'scenes', ['created_at'], unique=False)
    op.create_index(op.f('ix_scenes_distribution_mode'), 'scenes', ['distribution_mode'], unique=False)
    op.create_index(op.f('ix_scenes_is_active'), 'scenes', ['is_active'], unique=False)
    op.create_index(op.f('ix_scenes_name'), 'scenes', ['name'], unique=False)
    op.create_table('display_clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('display_type', sa.String(), nullable=True),
    sa.Column('discovery_method', sa.String(), nullable=True),
    sa.Column('auto_discovered', sa.Boolean(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('webhook_port', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('redis_distribution', sa.Boolean(), nullable=True),
    sa.Column('content_claiming', sa.Boolean(), nullable=True),
    sa.Column('client_version', sa.String(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('assigned_scene_id', sa.String(), nullable=True),
    sa.Column('current_content_hash', sa.String(), nullable=True),
    sa.Column('websocket_connection_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname', 'webhook_port', name='uq_display_clients_host_port')
    )
    op.create_index('ix_display_clients_assigned_scene', 'display_clients', ['assigned_scene_id'], unique=False)
    op.create_index(op.f('ix_display_clients_assigned_scene_id'), 'display_clients', ['assigned_scene_id'], unique=False)
    op.create_index(op.f('ix_display_clients_auto_discovered'), 'display_clients', ['auto_discovered'], unique=False)
    op.create_index('ix_display_clients_capabilities', 'display_clients', ['redis_distribution', 'content_claiming'], unique=False)
    op.create_index(op.f('ix_display_clients_client_version'), 'display_clients', ['client_version'], unique=False)
    op.create_index(op.f('ix_display_clients_content_claiming'), 'display_clients', ['content_claiming'], unique=False)
    op.create_index(op.f('ix_display_clients_created_at'), 'display_clients', ['created_at'], unique=False)
    op.create_index(op.f('ix_display_clients_discovery_method'), 'display_clients', ['discovery_method'], unique=False)
    op.create_index(op.f('ix_display_clients_display_type'), 'display_clients', ['display_type'], unique=False)
    op.create_index(op.f('ix_display_clients_hostname'), 'display_clients', ['hostname'], unique=False)
    op.create_index(op.f('ix_display_clients_is_online'), 'display_clients', ['is_online'], unique=False)
    op.create_index(op.f('ix_display_clients_last_seen'), 'display_clients', ['last_seen'], unique=False)
    op.create_index(op.f('ix_display_clients_location'), 'display_clients', ['location'], unique=False)
    op.create_index(op.f('ix_display_clients_name'), 'display_clients', ['name'], unique=False)
    op.create_index('ix_display_clients_online_seen', 'display_clients', ['is_online', 'last_seen'], unique=False)
    op.create_index(op.f('ix_display_clients_orientation'), 'display_clients', ['orientation'], unique=False)
    op.create_index(op.f('ix_display_clients_redis_distribution'), 'display_clients', ['redis_distribution'], unique=False)
    op.create_index('ix_display_clients_type_discovery', 'display_clients', ['display_type', 'discovery_method'], unique=False)
    op.create_index(op.f('ix_display_clients_websocket_connection_id'), 'display_clients', ['websocket_connection_id'], unique=False)
    op.create_table('display_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_client_id', sa.String(), nullable=True),
    sa.Column('current_scene', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('last_content_update', sa.DateTime(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('signal_strength', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['display_client_id'], ['display_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_display_status_created_at'), 'display_status', ['created_at'], unique=False)
    op.create_index(op.f('ix_display_status_current_scene'), 'display_status', ['current_scene'], unique=False)
    op.create_table('content_leases',
    sa.Column('lease_id', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('display_id', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('distribution_mode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['display_id'], ['display_clients.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('lease_id'),
    sa.UniqueConstraint('scene_id', 'display_id', 'content_id', name='uq_content_leases_assignment')
    )
    op.create_index(op.f('ix_content_leases_acknowledged_at'), 'content_leases', ['acknowledged_at'], unique=False)
    op.create_index('ix_content_leases_active', 'content_leases', ['status', 'assigned_at'], unique=False)
    op.create_index(op.f('ix_content_leases_assigned_at'), 'content_leases', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_content_leases_assignment_id'), 'content_leases', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_content_leases_content_id'), 'content_leases', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_leases_distribution_mode'), 'content_leases', ['distribution_mode'], unique=False)
    op.create_index(op.f('ix_content_leases_expires_at'), 'content_leases', ['expires_at'], unique=False)
    op.create_index('ix_content_leases_scene_display', 'content_leases', ['scene_id', 'display_id'], unique=False)
    op.create_index(op.f('ix_content_leases_status'), 'content_leases', ['status'], unique=False)
    op.create_index('ix_content_leases_status_expires', 'content_leases', ['status', 'expires_at'], unique=False)
    op.create_table('distribution_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('epoch_id', sa.Integer(), nullable=True),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'content_id', 'epoch_id', name='uq_distribution_queue_content')
    )
    op.create_index('ix_distribution_queue_claimed', 'distribution_queue', ['claimed_by', 'claimed_at'], unique=False)
    op.create_index(op.f('ix_distribution_queue_claimed_at'), 'distribution_queue', ['claimed_at'], unique=False)
    op.create_index(op.f('ix_distribution_queue_claimed_by'), 'distribution_queue', ['claimed_by'], unique=False)
    op.create_index(op.f('ix_distribution_queue_content_id'), 'distribution_queue', ['content_id'], unique=False)
    op.create_index(op.f('ix_distribution_queue_created_at'), 'distribution_queue', ['created_at'], unique=False)
    op.create_index('ix_distribution_queue_epoch', 'distribution_queue', ['epoch_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_distribution_queue_epoch_id'), 'distribution_queue', ['epoch_id'], unique=False)
    op.create_index(op.f('ix_distribution_queue_queue_position'), 'distribution_queue', ['queue_position'], unique=False)
    op.create_index('ix_distribution_queue_scene_position', 'distribution_queue', ['scene_id', 'queue_position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribution_queue')
    op.drop_table('content_leases')
    op.drop_table('display_status')
    op.drop_table('display_clients')
    op.drop_table('scenes')
    op.drop_table('overlays')
    op.drop_table('channels')
    # ### end Alembic commands ###
