"""add scheduler tables

Revision ID: 3c8b4f7ffefc
Revises: 8ae5e4a6c326
Create Date: 2026-01-28 21:52:31.218911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c8b4f7ffefc'
down_revision: Union[str, Sequence[str], None] = '8ae5e4a6c326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
    sa.Column('affected_scenes', sa.JSON(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('trigger_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_executions_completed_at'), 'scheduler_executions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_scheduler_executions_id'), 'scheduler_executions', ['id'], unique=False)
    op.create_index(op.f('ix_scheduler_executions_job_id'), 'scheduler_executions', ['job_id'], unique=False)
    op.create_index('ix_scheduler_executions_job_status', 'scheduler_executions', ['job_id', 'status'], unique=False)
    op.create_index('ix_scheduler_executions_started', 'scheduler_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_scheduler_executions_started_at'), 'scheduler_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_scheduler_executions_status'), 'scheduler_executions', ['status'], unique=False)
    op.create_index(op.f('ix_scheduler_executions_trigger_reason'), 'scheduler_executions', ['trigger_reason'], unique=False)
    op.create_index('ix_scheduler_executions_worker', 'scheduler_executions', ['worker_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_scheduler_executions_worker_id'), 'scheduler_executions', ['worker_id'], unique=False)
    op.create_table('scheduler_job_scene_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('refresh_method', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'scene_id', name='uq_scheduler_job_scene')
    )
    op.create_index(op.f('ix_scheduler_job_scene_assignments_created_at'), 'scheduler_job_scene_assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_scheduler_job_scene_assignments_id'), 'scheduler_job_scene_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_scheduler_job_scene_assignments_job_id'), 'scheduler_job_scene_assignments', ['job_id'], unique=False)
    op.create_index(op.f('ix_scheduler_job_scene_assignments_priority'), 'scheduler_job_scene_assignments', ['priority'], unique=False)
    op.create_index(op.f('ix_scheduler_job_scene_assignments_refresh_method'), 'scheduler_job_scene_assignments', ['refresh_method'], unique=False)
    op.create_index(op.f('ix_scheduler_job_scene_assignments_scene_id'), 'scheduler_job_scene_assignments', ['scene_id'], unique=False)
    op.create_index('ix_scheduler_scene_assignments_job_scene', 'scheduler_job_scene_assignments', ['job_id', 'scene_id'], unique=False)
    op.create_index('ix_scheduler_scene_assignments_scene_priority', 'scheduler_job_scene_assignments', ['scene_id', 'priority'], unique=False)
    op.create_table('scheduler_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('freq_unit', sa.String(), nullable=False),
    sa.Column('freq_value', sa.Integer(), nullable=False),
    sa.Column('approx_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('timezone_name', sa.String(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('run_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('jitter_seconds', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('action_config', sa.JSON(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduler_jobs_action', 'scheduler_jobs', ['action_type', 'enabled'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_action_type'), 'scheduler_jobs', ['action_type'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_consecutive_failures'), 'scheduler_jobs', ['consecutive_failures'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_created_at'), 'scheduler_jobs', ['created_at'], unique=False)
    op.create_index('ix_scheduler_jobs_due', 'scheduler_jobs', ['enabled', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_enabled'), 'scheduler_jobs', ['enabled'], unique=False)
    op.create_index('ix_scheduler_jobs_failures', 'scheduler_jobs', ['consecutive_failures', 'enabled'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_freq_unit'), 'scheduler_jobs', ['freq_unit'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_id'), 'scheduler_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_last_run_at'), 'scheduler_jobs', ['last_run_at'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_last_success_at'), 'scheduler_jobs', ['last_success_at'], unique=False)
    op.create_index('ix_scheduler_jobs_locked', 'scheduler_jobs', ['locked_until', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_locked_until'), 'scheduler_jobs', ['locked_until'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_name'), 'scheduler_jobs', ['name'], unique=False)
    op.create_index(op.f('ix_scheduler_jobs_next_run_at'), 'scheduler_jobs', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.add_column('content_leases', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_content_leases_display_id'), 'content_leases', ['display_id'], unique=False)
    op.create_index(op.f('ix_content_leases_id'), 'content_leases', ['id'], unique=False)
    op.create_index(op.f('ix_content_leases_lease_id'), 'content_leases', ['lease_id'], unique=True)
    op.create_index(op.f('ix_content_leases_scene_id'), 'content_leases', ['scene_id'], unique=False)
    op.drop_constraint(op.f('content_leases_display_id_fkey'), 'content_leases', type_='foreignkey')
    op.drop_constraint(op.f('content_leases_scene_id_fkey'), 'content_leases', type_='foreignkey')
    op.alter_column('display_clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_display_clients_id'), 'display_clients', ['id'], unique=False)
    op.drop_constraint(op.f('display_clients_assigned_scene_id_fkey'), 'display_clients', type_='foreignkey')
    op.drop_column('display_clients', 'device_type')
    op.create_index(op.f('ix_display_scene_images_created_at'), 'display_scene_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_display_scene_images_expires_at'), 'display_scene_images', ['expires_at'], unique=False)
    op.create_index(op.f('ix_display_scene_images_id'), 'display_scene_images', ['id'], unique=False)
    op.add_column('display_status', sa.Column('hardware', sa.JSON(), nullable=True))
    op.add_column('display_status', sa.Column('current_image', sa.JSON(), nullable=True))
    op.add_column('display_status', sa.Column('resolution', sa.JSON(), nullable=True))
    op.alter_column(
        'display_status',
        'id',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
        postgresql_using='id::integer',
    )
    op.create_index(op.f('ix_display_status_id'), 'display_status', ['id'], unique=False)
    op.drop_constraint(op.f('display_status_display_client_id_fkey'), 'display_status', type_='foreignkey')
    op.drop_column('display_status', 'signal_strength')
    op.drop_column('display_status', 'content_hash')
    op.drop_column('display_status', 'temperature')
    op.drop_column('display_status', 'battery_level')
    op.drop_column('display_status', 'last_content_update')
    op.drop_column('display_status', 'display_client_id')
    op.alter_column(
        'distribution_queue',
        'id',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
        postgresql_using='id::integer',
    )
    op.alter_column('distribution_queue', 'epoch_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_distribution_queue_id'), 'distribution_queue', ['id'], unique=False)
    op.create_index(op.f('ix_distribution_queue_scene_id'), 'distribution_queue', ['scene_id'], unique=False)
    op.drop_constraint(op.f('distribution_queue_scene_id_fkey'), 'distribution_queue', type_='foreignkey')
    op.add_column('overlays', sa.Column('description', sa.String(), nullable=True))
    op.add_column('overlays', sa.Column('channel', sa.JSON(), nullable=True))
    op.add_column('overlays', sa.Column('path_root', sa.String(), nullable=True))
    op.create_index(op.f('ix_overlays_id'), 'overlays', ['id'], unique=False)
    op.drop_column('overlays', 'config')
    op.drop_column('overlays', 'overlay_type')
    op.add_column('scenes', sa.Column('update_strategy', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('push_fallback_poll_seconds', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_scenes_id'), 'scenes', ['id'], unique=False)
    op.create_index(op.f('ix_scenes_update_strategy'), 'scenes', ['update_strategy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenes_update_strategy'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_id'), table_name='scenes')
    op.drop_column('scenes', 'push_fallback_poll_seconds')
    op.drop_column('scenes', 'update_strategy')
    op.add_column('overlays', sa.Column('overlay_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('overlays', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_overlays_id'), table_name='overlays')
    op.drop_column('overlays', 'path_root')
    op.drop_column('overlays', 'channel')
    op.drop_column('overlays', 'description')
    op.create_foreign_key(op.f('distribution_queue_scene_id_fkey'), 'distribution_queue', 'scenes', ['scene_id'], ['id'])
    op.drop_index(op.f('ix_distribution_queue_scene_id'), table_name='distribution_queue')
    op.drop_index(op.f('ix_distribution_queue_id'), table_name='distribution_queue')
    op.alter_column('distribution_queue', 'epoch_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('distribution_queue', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('display_status', sa.Column('display_client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('display_status', sa.Column('last_content_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('display_status', sa.Column('battery_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('display_status', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('display_status', sa.Column('content_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('display_status', sa.Column('signal_strength', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('display_status_display_client_id_fkey'), 'display_status', 'display_clients', ['display_client_id'], ['id'])
    op.drop_index(op.f('ix_display_status_id'), table_name='display_status')
    op.alter_column('display_status', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('display_status', 'resolution')
    op.drop_column('display_status', 'current_image')
    op.drop_column('display_status', 'hardware')
    op.drop_index(op.f('ix_display_scene_images_id'), table_name='display_scene_images')
    op.drop_index(op.f('ix_display_scene_images_expires_at'), table_name='display_scene_images')
    op.drop_index(op.f('ix_display_scene_images_created_at'), table_name='display_scene_images')
    op.add_column('display_clients', sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('display_clients_assigned_scene_id_fkey'), 'display_clients', 'scenes', ['assigned_scene_id'], ['id'])
    op.drop_index(op.f('ix_display_clients_id'), table_name='display_clients')
    op.alter_column('display_clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('content_leases_scene_id_fkey'), 'content_leases', 'scenes', ['scene_id'], ['id'])
    op.create_foreign_key(op.f('content_leases_display_id_fkey'), 'content_leases', 'display_clients', ['display_id'], ['id'])
    op.drop_index(op.f('ix_content_leases_scene_id'), table_name='content_leases')
    op.drop_index(op.f('ix_content_leases_lease_id'), table_name='content_leases')
    op.drop_index(op.f('ix_content_leases_id'), table_name='content_leases')
    op.drop_index(op.f('ix_content_leases_display_id'), table_name='content_leases')
    op.drop_column('content_leases', 'id')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_scheduler_jobs_next_run_at'), table_name='scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_jobs_name'), table_name='scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_jobs_locked_until'), table_name='scheduler_jobs')
    op.drop_index('ix_scheduler_jobs_locked', table_name='scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_jobs_last_success_at'), table_name='scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_jobs_last_run_at'), table_name='scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_jobs_id'), table_name='scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_jobs_freq_unit'), table_name='scheduler_jobs')
    op.drop_index('ix_scheduler_jobs_failures', table_name='scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_jobs_enabled'), table_name='scheduler_jobs')
    op.drop_index('ix_scheduler_jobs_due', table_name='scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_jobs_created_at'), table_name='scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_jobs_consecutive_failures'), table_name='scheduler_jobs')
    op.drop_index(op.f('ix_scheduler_jobs_action_type'), table_name='scheduler_jobs')
    op.drop_index('ix_scheduler_jobs_action', table_name='scheduler_jobs')
    op.drop_table('scheduler_jobs')
    op.drop_index('ix_scheduler_scene_assignments_scene_priority', table_name='scheduler_job_scene_assignments')
    op.drop_index('ix_scheduler_scene_assignments_job_scene', table_name='scheduler_job_scene_assignments')
    op.drop_index(op.f('ix_scheduler_job_scene_assignments_scene_id'), table_name='scheduler_job_scene_assignments')
    op.drop_index(op.f('ix_scheduler_job_scene_assignments_refresh_method'), table_name='scheduler_job_scene_assignments')
    op.drop_index(op.f('ix_scheduler_job_scene_assignments_priority'), table_name='scheduler_job_scene_assignments')
    op.drop_index(op.f('ix_scheduler_job_scene_assignments_job_id'), table_name='scheduler_job_scene_assignments')
    op.drop_index(op.f('ix_scheduler_job_scene_assignments_id'), table_name='scheduler_job_scene_assignments')
    op.drop_index(op.f('ix_scheduler_job_scene_assignments_created_at'), table_name='scheduler_job_scene_assignments')
    op.drop_table('scheduler_job_scene_assignments')
    op.drop_index(op.f('ix_scheduler_executions_worker_id'), table_name='scheduler_executions')
    op.drop_index('ix_scheduler_executions_worker', table_name='scheduler_executions')
    op.drop_index(op.f('ix_scheduler_executions_trigger_reason'), table_name='scheduler_executions')
    op.drop_index(op.f('ix_scheduler_executions_status'), table_name='scheduler_executions')
    op.drop_index(op.f('ix_scheduler_executions_started_at'), table_name='scheduler_executions')
    op.drop_index('ix_scheduler_executions_started', table_name='scheduler_executions')
    op.drop_index('ix_scheduler_executions_job_status', table_name='scheduler_executions')
    op.drop_index(op.f('ix_scheduler_executions_job_id'), table_name='scheduler_executions')
    op.drop_index(op.f('ix_scheduler_executions_id'), table_name='scheduler_executions')
    op.drop_index(op.f('ix_scheduler_executions_completed_at'), table_name='scheduler_executions')
    op.drop_table('scheduler_executions')
    # ### end Alembic commands ###
